language: php

php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "hhvm"

branches:
  only:
    - master
    - develop

install:
  - composer install

script:
  - ./vendor/bin/phpunit

matrix:
  allow_failures:
    - php: "5.3"

